# Generated by Django 2.2.16 on 2022-05-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220509_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=36, null=True, verbose_name='Проверочный код'),
        ),
    ]
